[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sig"
path = "./src/header_signature.rs"
doctest = false
test = false
doc = false

[lib]
name = "crawler"
path = "./src/lib.rs"
doctest = false
test = false
doc = false

[dependencies]
common.workspace = true

#headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
reqwest = { workspace = true, features = ["json", "cookies", "gzip", "http2"] }
reqwest-retry.workspace = true
reqwest-middleware = { workspace = true, features = ["json"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
thiserror.workspace = true
openssl.workspace = true
chrono.workspace = true
web-bot-auth.workspace = true
indexmap.workspace = true
ed25519-dalek.workspace = true
