[package]
name = "openid_connect"
version = "0.1.0"
edition = "2024"

[lib]
name = "openid_connect"
path = "./src/lib.rs"
doctest = false
test = false
doc = false

[dependencies]
mongodb_connector.workspace = true
common.workspace = true

openidconnect.workspace = true
async-trait.workspace = true
tracing.workspace = true
tokio.workspace = true
thiserror.workspace = true
