name: Deploy

inputs:
  github-token:
    type: string
    required: true
    description: "Github Actions token"
  deployment-stage:
    type: choice
    required: true
    description: "The environment to install the systemd services into"
    options: ["release", "beta"]
  docker-volume-path:
    type: string
    required: true
    description: "Path on machine to Docker mounts"
  env-file:
    type: string
    required: true
    description: "env file contents"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - uses: actions/checkout@v6
      with:
        repository: almostprohibited/toolbox
        ref: main
        path: ./.toolbox
    - name: Login to ghcr.io
      run: echo ${{ inputs.github-token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Update and deploy MongoDB
      if: inputs.deployment-stage == 'release'
      run: |
        set -ueo pipefail

        cd ./.toolbox/backend

        export VOLUME_PATH=${{ inputs.docker-volume-path }}

        mkdir -p $VOLUME_PATH/prometheus
        touch $VOLUME_PATH/prometheus/prometheus.yml || true

        docker compose -f docker-compose.yaml pull mongo mongo-express prometheus grafana
        docker compose -f docker-compose.yaml down mongo mongo-express prometheus grafana
        docker compose -f docker-compose.yaml up -d mongo mongo-express prometheus grafana
      shell: bash
    - name: Update and deploy backend
      run: |
        set -ueo pipefail

        cd ./.toolbox/backend

        if [ "${{ inputs.deployment-stage }}" = "beta" ]; then
          export RUST_LOG=debug
          echo "${{ inputs.env-file }}" > ${{ inputs.docker-volume-path }}/.env.beta
        else
          echo "${{ inputs.env-file }}" > ${{ inputs.docker-volume-path }}/.env.release
        fi

        export VOLUME_PATH=${{ inputs.docker-volume-path }}
        export STAGE=${{ inputs.deployment-stage }}

        docker compose -f docker-compose.yaml pull backend-${{ inputs.deployment-stage }}
        docker compose -f docker-compose.yaml down backend-${{ inputs.deployment-stage }}
        docker compose -f docker-compose.yaml up -d backend-${{ inputs.deployment-stage }}
      shell: bash
    - name: Clean images
      run: docker image prune -f
      shell: bash
