mod aag_canada;
mod al_simmons;
mod bartons_big_country;
mod budget_shooter_supply;
mod bullseye_north;
mod cabin_creek_supply;
mod canadas_gun_store;
mod canfirearm;
mod clinton_sporting_goods;
mod crafm;
mod dante_sports;
mod dominion_outdoors;
mod doubletap_sports;
mod ds_tactical;
mod easthill_outdoors;
mod ellwood_epps;
mod firearms_outlet_canada; // why is FOC so bloated it uses so much memory in a browser window
mod frontier_firearms;
mod fwgc;
mod g4c_gun_store;
mod general_gun;
mod gobles;
mod goldnloan;
mod great_north_gun;
mod international_shooting_supplies;
mod intersurplus;
mod italian_sporting_goods; // they have arsenalforce in their robots.txt
mod lanz_shooting_supplies;
mod latulippe;
mod lever_arms;
mod liangjian;
mod londero_sports;
mod magdump;
mod marstar;
mod nechako_outdoors;
mod northern_elite;
mod parts_only;
mod pd_enterprises;
mod range_arts;
mod rangeview_sports;
mod rdsc;
mod reliable_gun;
mod shooters_choice; // reminder, do full refreshes in browser once in a while, their site is quite bloated
mod sights_and_arms;
mod sj_hardware;
mod soley_outdoors;
mod swamp_donkey_outdoors;
mod tenda;
mod tesro;
mod the_ammo_source;
mod the_gun_dealer;
mod tillsonburg_gun_shop;
mod true_north_arms;
mod uxbridge_arms;
mod victory_ridge_sports;
mod wolverine_supplies;
mod x_reload;

pub use aag_canada::AagCanada;
pub use al_simmons::AlSimmons;
pub use bartons_big_country::BartonsBigCountry;
pub use budget_shooter_supply::BudgetShooterSupply;
pub use bullseye_north::BullseyeNorth;
pub use cabin_creek_supply::CabinCreekSupply;
pub use canadas_gun_store::CanadasGunStore;
pub use canfirearm::CanFirearm;
pub use clinton_sporting_goods::ClintonSportingGoods;
pub use crafm::Crafm;
pub use dante_sports::DanteSports;
pub use dominion_outdoors::DominionOutdoors;
pub use doubletap_sports::DoubleTapSports;
pub use ds_tactical::DsTactical;
pub use easthill_outdoors::EasthillOutdoors;
pub use ellwood_epps::EllwoodEpps;
pub use firearms_outlet_canada::FirearmsOutletCanada;
pub use frontier_firearms::FrontierFirearms;
pub use fwgc::Fwgc;
pub use g4c_gun_store::G4CGunStore;
pub use general_gun::GeneralGun;
pub use gobles::Gobles;
pub use goldnloan::GoldNLoan;
pub use great_north_gun::GreatNorthGun;
pub use international_shooting_supplies::InternationalShootingSupplies;
pub use intersurplus::InterSurplus;
pub use italian_sporting_goods::ItalianSportingGoods;
pub use lanz_shooting_supplies::LanzShootingSupplies;
pub use latulippe::Latulippe;
pub use lever_arms::LeverArms;
pub use liangjian::Liangjian;
pub use londero_sports::LonderoSports;
pub use magdump::MagDump;
pub use marstar::Marstar;
pub use nechako_outdoors::NechakoOutdoors;
pub use northern_elite::NorthernElite;
pub use parts_only::PartsOnly;
pub use pd_enterprises::PDEnterprises;
pub use range_arts::RangeArts;
pub use rangeview_sports::RangeviewSports;
pub use rdsc::Rdsc;
pub use reliable_gun::ReliableGun;
pub use shooters_choice::ShootersChoice;
pub use sights_and_arms::SightsAndArms;
pub use sj_hardware::SJHardware;
pub use soley_outdoors::SoleyOutdoors;
pub use swamp_donkey_outdoors::SwampDonkeyOutdoors;
pub use tenda::Tenda;
pub use tesro::Tesro;
pub use the_ammo_source::TheAmmoSource;
pub use the_gun_dealer::TheGunDealer;
pub use tillsonburg_gun_shop::Tillsonburg;
pub use true_north_arms::TrueNorthArms;
pub use uxbridge_arms::UxbridgeArms;
pub use victory_ridge_sports::VictoryRidgeSports;
pub use wolverine_supplies::WolverineSupplies;
pub use x_reload::XReload;
