name: Package

inputs:
  github-token:
    type: string
    required: true
    description: "Github Actions token"
  deployment-stage:
    type: choice
    required: true
    description: "The environment to install the systemd services into"
    options: ["release", "beta"]
  artifact-id:
    type: string
    required: true
    description: "The artifact ID from the previous build step containing Rust binaries"

runs:
  using: composite
  steps:
    # this is not a typo, first checkout checkouts this backend repo
    # the other checkout grabs the toolbox package
    - uses: actions/checkout@v6
    - uses: actions/checkout@v6
      with:
        repository: almostprohibited/toolbox
        ref: main
        path: ./.toolbox
    - uses: actions/download-artifact@v8
      name: Download built files
      with:
        artifact-ids: ${{ inputs.artifact-id }}
        path: ./.download
    - run: |
        mv ./.download/* ./.toolbox/backend/
      shell: bash
    - parallel:
      - name: Build API Docker image
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        run: |
          set -ueo pipefail
  
          docker run --privileged --rm tonistiigi/binfmt --install arm64
  
          cd ./.toolbox/backend/
  
          docker build \
            --pull \
            --no-cache \
            --build-arg API_BINARY_NAME=api \
            --platform=linux/arm64 \
            -f Dockerfile-backend-web.dockerfile \
            -t ghcr.io/almostprohibited/backend-web:${{ inputs.deployment-stage }} \
            .
  
          echo ${{ inputs.github-token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
          docker push ghcr.io/almostprohibited/backend-web:${{ inputs.deployment-stage }}
        shell: bash
      - name: Build indexer Docker image
        if: inputs.deployment-stage == 'release'
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        run: |
          set -ueo pipefail
  
          docker run --privileged --rm tonistiigi/binfmt --install arm64
  
          cd ./.toolbox/backend/
  
          docker build \
            --pull \
            --no-cache \
            --build-arg INDEXER_BINARY_NAME=indexer \
            --platform=linux/arm64 \
            -f Dockerfile-backend-indexer.dockerfile \
            -t ghcr.io/almostprohibited/backend-indexer:${{ inputs.deployment-stage }} \
            .
  
          echo ${{ inputs.github-token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
          docker push ghcr.io/almostprohibited/backend-indexer:${{ inputs.deployment-stage }}
        shell: bash
    - name: Clean old package versions
      uses: actions/delete-package-versions@v5
      with:
        owner: almostprohibited
        package-name: backend
        package-type: container
        min-versions-to-keep: 1
        delete-only-untagged-versions: true
