pub const DISCORD_CONTACT_WEBHOOK_URL: &str = "DISCORD_CONTACT_WEBHOOK_URL";
pub const DISCORD_INDEXER_WEBHOOK_URL: &str = "DISCORD_INDEXER_WEBHOOK_URL";
pub const CLOUDFLARE_TURNSTILE_SECRET_KEY: &str = "CLOUDFLARE_TURNSTILE_SECRET_KEY";
pub const OIDC_CLIENT_ID_DISCORD: &str = "OIDC_CLIENT_ID_DISCORD";
pub const OIDC_CLIENT_SECRET_DISCORD: &str = "OIDC_CLIENT_SECRET_DISCORD";
pub const PROXY_ADDRESS: &str = "PROXY_ADDRESS";

pub const CRAWL_COOLDOWN_SECS: u64 = 10;
